#! /usr/bin/env node

const path= require('path');
const defConf= {
	presets: [ 'es2015', 'react' ],
	plugins: [ 'transform-object-rest-spread' ]
};

require('babel-register')();

const fileName= process.argv[2];

let App;

console.log(path.resolve(fileName));

try {
	App= require(path.resolve(fileName)).default;

	if(!App) {
		throw new Error("You need to export an app component. (Eg - export default class App extends React.Component {})");
	}

} catch(e) {
	console.log(e);
	process.exit(1);
}

const ServerWrapper= App.NodeServer || require('./app.jsx').NodeServer;

const server= new ServerWrapper(App);

server.createServer();
server.start();

