#! /usr/bin/env node

const path= require('path');
const defConf= {
	presets: [ 'es2015', 'react' ],
	plugins: [ 'transform-object-rest-spread' ]
};

require('babel-register')({

	ignore: (name) => {

		if(name.includes('node_modules/plasmajs')) {
			return false;
		}

		if(name.includes('node_modules')) {
			return true;
		}

		return false;
	}
});

const fileName= process.argv[2];

let App;

try {

	App= require(path.resolve(fileName)).default;

	if(!App) {
		throw new Error("You need to export a React component class");
	}

} catch(e) {

	console.log("ERROR:", e);

	process.exit(1);
}

const ServerWrapper= App.NodeServer || require('./app.jsx').NodeServer;

const server= new ServerWrapper(App);

server.createServer();
server.start();

